### ISSUE TITLE
Refactor the code and file structure

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#1]
The code for the portfolio website is kept in only one file i.e App.js. But we need to divide the code in different modules just in the way react allows.

The code contains all the information about different sections like navbar, contact section, footer etc. Just create new files like Navbar.js, Contact.js and put the code into it.

[x] Navbar
[x] Main Section
[x] About Section
[x] Services Section 
[x] Skills Section
[x] Projects Section
[x] Contact Section
[x] Footer

**Comment by khushali77** [comment]
Can I work on this issue?

**Comment by TheDeveloperD** [comment]
OK. I am assinging you this task.

**Comment by TheDeveloperD** [comment]
Thank You @khushali77 .
