### ISSUE TITLE
Design the Footer

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#11]
Design the footer of the website. The css should be kept in a new file named Footer.css inside the css folder.

Website color theme:
1. white
2. crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme.

Make sure you attach a snap of the changes made by you in your PR.

**Comment by mtahashahid** [comment]
Hi, there. I would love to do this.
can I do this?

**Comment by TheDeveloperD** [comment]
Ya Sure. I am assigning this task to you. 
Thank you taking interest in open source contribution.

**Comment by SoundaryaKhanapur** [comment]
May I do this?

**Comment by TheDeveloperD** [comment]
Currently this issue is assigned to someone else. 
@SoundaryaKhanapur You may take a look at other issues. If you are searching for good first issues then #3 is a good one for you and is still open.
