### ISSUE TITLE
Prepare a Documentation

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#12]
Prepare a documentation for normal people out there looking for a good porfolio.

- It should include the info like change #me to your name, change email in contact page etc. Also It should contain the file names they need to change.

- Then prepare a section in doc for making it ready for deployment i.e. how to see the changes and then creating the build.

Take your time and prepare the doc well so that even a non-developer finds it easy to use. 

Create a new file documentation.md for the documentation. Later on we can merge it in readme.

**Comment by adit19shah** [comment]
@TheDeveloperD I want to work on this issue.

**Comment by dishantvyas15** [comment]
Issue assigned to @adit19shah 
Thanks.
