### ISSUE TITLE
Bug in Services Section

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#18]
There is an issue in services section. When we hover the card in services section, the text inside the card is not visible. 
Change the services.css file bit to remove the bug and improve the design a little bit.

Website color theme:
1. white
2. crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme.

Attach a snap of changes made by you in your PR.

**Comment by viogustian** [comment]
please assign it to me

**Comment by TheDeveloperD** [comment]
OK I am assigning this task to you.

**Comment by TheDeveloperD** [comment]
Thank you for your contribution.
