### ISSUE TITLE
Logo for the portfolio

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#19]
Create a logo for this portfolio to be shown on title bar(browser) and on the navbar.

Please don't plagiarise or copy the from any other sources. Show your logo designing skills.

**Comment by CoHarsh** [comment]
Can I work on this logo thing?
I want to give try to his.

**Comment by TheDeveloperD** [comment]
Ya sure. I will assign this task to you.

**Comment by CoHarsh** [comment]
Can you please give some description about the logo,
How that looks like and should I put an Image of a model or just make a name logo?

**Comment by Hussain6** [comment]
Can you assign this to me?

**Comment by TheDeveloperD** [comment]
@CoHarsh It should be a general logo like we get a general avatar in other apps until we put our own profile. It should be creative and should match to portfolio. You can update your local repo and see the updated navbar and then decide how you would design the logo.

**Comment by TheDeveloperD** [comment]
@Hussain6 I am assigning this task to you too. That would provide a choice for two logos for the users of portfolio.

**Comment by CoHarsh** [comment]
Hey @TheDeveloperD I have updated the main section and also put a logo in the site:
Please take a look:
![image](https://user-images.githubusercontent.com/73811116/135814379-b42bf672-10ca-4160-815f-9668a771da5c.png)
any feedback?

**Comment by TheDeveloperD** [comment]
@CoHarsh Main section looks awesome. 

But the we don't need this kind of logo. This logo shows MSTC but portfolio is for user's personal info. It should be general avatar. You can search google for 'profile avatar logo' and take hint. 

You may make a PR for the Main section.
