### ISSUE TITLE
Design the Navbar

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#2]
Currently the navbar is only the text and no design.

Design the Navbar using css and js(if required). The css should be kept in a new file named Navbar.css inside the css folder.

Website color theme: 
1) white
2) crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme.

**Comment by CoHarsh** [comment]
I have understood the issue and I think I can do this.
can you assign this issue to me?

**Comment by TheDeveloperD** [comment]
> I have understood the issue and I think I can do this. can you assign this issue to me?

OK. I am assigning you this task.

**Comment by CoHarsh** [comment]
![Screenshot (528)](https://user-images.githubusercontent.com/73811116/135709260-c54643ee-682d-4b60-9cd8-68c440bf1555.png)
![Screenshot (529)](https://user-images.githubusercontent.com/73811116/135709262-c7f724e1-863f-4080-a9f3-79657c3ea8bd.png)
can you please give feedback on this?
what should I do next ,push the code or modify this further? @TheDeveloperD

**Comment by TheDeveloperD** [comment]
@CoHarsh  The navbar looks awesome. I saw it in the mail I received. Why did you take back your comment?

**Comment by CoHarsh** [comment]
I made another as there are so many bugs and it is not responsive
I am commiting another navbar.
Please check it out and let me know if I get back to previous or not

Harsh

**Comment by TheDeveloperD** [comment]
Oh ok, you may make the navbar as you like. I just saw a beautiful design previously so asked about it.

**Comment by TheDeveloperD** [comment]
Thank you for your contributions.
