### ISSUE TITLE
Deploy the Project on vercel or netlify 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [MSTC-DA-IICT/react-portfolio#20]
**Is your feature request related to a problem? Please describe.**
As when we deploy the project is lots more easy for contributors to find bug and fix them 

**Describe the solution you'd like**
Any deployment platform of your preference will work

**Comment by TheDeveloperD** [comment]
Anyone can just clone this repo and find the bugs by running the application. But I find your suggestion is a good one and we can deploy the app. If you wish I can assign this to you @rohan-kulkarni-25.
