### ISSUE TITLE
Addition of progress bar in skills section

### ISSUE THREAD

**Issue by priyansh71** [MSTC-DA-IICT/react-portfolio#23]
**Is your feature request related to a problem? Please describe.**
It's not an issue, this is just a feature which would improve the UI of the project

**Describe the solution you'd like**
A progress bar which shows the user's techstack progress instead of percentage numbers in the #skills section.

**Describe alternatives you've considered**
On top of that, different colored progress bars could be added for each skill.

**Additional context**
Example uni-colored progress bars are attached here:

<img width="699" alt="Screenshot 2021-10-04 at 15 17 01" src="https://user-images.githubusercontent.com/77532581/135830667-80ddb8b5-1c66-454b-82cd-06048b5cae9d.png">

**Comment by priyansh71** [comment]
If you want this implementation, assign it to me, I'd like to work on it.

**Comment by TheDeveloperD** [comment]
Ya this is what I was searching for. I am assigning this task to you. 
Try to implement it in a simpler way(easy to understand) so that if someone wish to add a skill he can easily do it in code.

**Comment by TheDeveloperD** [comment]
Main theme colors of website are 1. White 2. Crimson.  So try to abide by this theme.

**Comment by priyansh71** [comment]
Can this issue be closed now?
