### ISSUE TITLE
Sticky navbar on scroll

### ISSUE THREAD

**Issue by udz-codes** [MSTC-DA-IICT/react-portfolio#27]
**Is your feature request related to a problem? Please describe.**
To make the navbar more accessible throughout the scrolling journey of the website, we can make it sticky.

**Describe the solution you'd like**
Make the navbar sticky

**Comment by udz-codes** [comment]
> **Is your feature request related to a problem? Please describe.** To make the navbar more accessible throughout the scrolling journey of the website, we can make it sticky.
> 
> **Describe the solution you'd like** Make the navbar sticky

If you like it, you can assign it to me and I can work on this.

**Comment by TheDeveloperD** [comment]
Ok so I am assigning this task to you
