### ISSUE TITLE
Design Main Section

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#3]
Currently the main section is only the text and no design.

Design the main section using css and js(if required). The css should be kept in a new file named Main.css inside the css folder.
The main section should look appealing as it is the first thing that user sees as website loads.

Website color theme:
1. white
2. crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme.

**Comment by chintansuthar72** [comment]
I got the point well and I'm very delightful to make this awesome!
Warm request to assign this to me. will you do that ?

**Comment by TheDeveloperD** [comment]
Ya sure. I am assigning this task to you.

**Comment by chintansuthar72** [comment]
Sorry for inconvenience! but I'm not getting that i wanted. You can assign this to anyone.
Thanks for assigning. 😊

**Comment by SoundaryaKhanapur** [comment]
may I pick this up?

**Comment by TheDeveloperD** [comment]
Ya Sure. I am assigning this task to you. 
Thank you for showing you interest in open source.

**Comment by SoundaryaKhanapur** [comment]
I have added the design for about and skills section

**Comment by SoundaryaKhanapur** [comment]
![image](https://user-images.githubusercontent.com/36791174/135779808-58833e35-d014-4068-a19b-12db05ca8573.png)
removed about and skill design and styled main section as assigned. I have created a separate pull request for this.

**Comment by TheDeveloperD** [comment]
Thank you for your contributions.
