### ISSUE TITLE
Navbar overflowing on <900px screens

### ISSUE THREAD

**Issue by priyansh71** [MSTC-DA-IICT/react-portfolio#32]
While working on #23 for the project, I came across the following bug-

**Describe the bug**
The navbar overflows on small sized devices which makes the text beneath it unreadable

**To Reproduce**
1. Choose a device with screen width <900 px or Resize the window to <900px width.
2. Scroll down to about me or skills section
3. See overflow

**Expected behavior**
The text beneath to be readable and the navbar elements to enter a toggle menu on resizing the window to <900px.

**Screenshots**

<img width="433" alt="Screenshot 2021-10-04 at 23 17 49" src="https://user-images.githubusercontent.com/77532581/135899418-60bf2dd8-80af-4d13-80ca-753ff2facaaf.png">

**Comment by priyansh71** [comment]
If you'd like a solution to this issue, I'd like to work on this.

**Comment by TheDeveloperD** [comment]
OK then, I am assigning this task to you.
