### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#4]
Currently the main section is only the text and no design.

Design the about section using css. The css should be kept in a new file named About.css inside the css folder.
The About section contains almost all the information needed except the design.

Website color theme:
1. white
2. crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme. 

When submitting a PR, please attach a snap of changes you made to the webpage.

**Comment by rishikeshreddyakkireddy** [comment]
I would like to work on this issue can you assign this to me?

**Comment by TheDeveloperD** [comment]
> I would like to work on this issue can you assign this to me?

Ok. I am assigning this task to you.

**Comment by TheDeveloperD** [comment]
@rishikeshreddyakkireddy any updates?

**Comment by khushali77** [comment]
If @rishikeshreddyakkireddy is not doing, then can you assign it to me?

**Comment by TheDeveloperD** [comment]
@khushali77 I'll just wait for his reply.

**Comment by TheDeveloperD** [comment]
@khushali77 I don't think he is not much active so you can start working on this issue. I am assigning this task to you.

**Comment by TheDeveloperD** [comment]
@khushali77 any updates?

**Comment by khushali77** [comment]
@TheDeveloperD you can assign it to someone else.

**Comment by Samay10** [comment]
@TheDeveloperD I would like to work on this issue.

**Comment by TheDeveloperD** [comment]
OK then I am assigning this task to you.

**Comment by TheDeveloperD** [comment]
Any updates? @Samay10

**Comment by TaniyaFaisal** [comment]
Hey! I would like to try this.

**Comment by TheDeveloperD** [comment]
Great. Assigning this task to you @kartiks26

**Comment by kartiks26** [comment]
@TheDeveloperD  was stuck in some crisis working now

**Comment by kartiks26** [comment]
![image](https://user-images.githubusercontent.com/84696578/137540353-6db817bc-53fa-4ed6-b67f-8ac7aa123eb5.png)

did it just having trouble with pull

**Comment by TheDeveloperD** [comment]
Please elaborate your problem
