### ISSUE TITLE
Images load

### ISSUE THREAD

**Issue by milekag01** [MSTC-DA-IICT/react-portfolio#48]
Image load after the content loads and since it is of large size, it takes some time to load without any loader/animation.

Reload the website to see the image load.
Images should load after the content loads and a loader should appear while the images loads.

**Comment by mstofirova** [comment]
hi, can i work in this issue?

**Comment by TheDeveloperD** [comment]
Yes you can, Assigning this task to you.

**Comment by TheDeveloperD** [comment]
It's better if loader is there for all images.
