### ISSUE TITLE
Design My Services Section

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#5]
Design the services section using css and js(if required). The css should be kept in a new file named Services.css inside the css folder.

The UI for this section should be eye catching. So a good amount of knowledge of css is required to work on this issue.

Website color theme:
1. white
2. crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme.

Make sure you attach a snap of the changes made by you in your PR.

**Comment by Ukesh-dev** [comment]
I would love to work on this issue.

**Comment by TheDeveloperD** [comment]
> I would love to work on this issue.

OK.  Then I am assigning this task to you.

**Comment by TheDeveloperD** [comment]
Thank You for the contribution.
