### ISSUE TITLE
Footer social media icons hover bug

### ISSUE THREAD

**Issue by KishanSeksaria** [MSTC-DA-IICT/react-portfolio#53]
Social media icons don't seem to respond how they were intended on hover. Here is a gif of the same. 

![Footer issue](https://user-images.githubusercontent.com/66475935/136549796-408f220e-2008-4620-81b3-8810ab659226.gif)

The animation also seems a bit over the top, it would be better to do something minimal.

**Comment by TheDeveloperD** [comment]
Assigning this task to @AdityaPandey03 as requested first.

**Comment by TheDeveloperD** [comment]
> I have a working one, pretty simple though, not too flashy

Add a snap of it here. Let me see it and if it looks good then we will merge it.

**Comment by kartiks26** [comment]
Is it resolved??

**Comment by aadishJ01** [comment]
Hey @TheDeveloperD, is this issue open? I am interested in working on it.

**Comment by TheDeveloperD** [comment]
Yes @aadishJ01 . You can work and make PR for solving this issue
