### ISSUE TITLE
Contact form on devices with width<880px

### ISSUE THREAD

**Issue by apupneja** [MSTC-DA-IICT/react-portfolio#55]
The contact form on devices with width less than 880px extends to 100% of the width and doesn't look visually appealing.

1. Go to web tools section of browser
2. Open the website on a device with width less than 880px
3. Scroll to Contact section.

White space on both right side and left side of the form would be more visually appealing.

**Screenshots**
![image](https://user-images.githubusercontent.com/51889135/136644062-f44ab55f-f962-43bd-9698-722e6c1049e6.png)

**Smartphone:**
 - Device: Oneplus7t
 - OS: Android 11
 - Browser: Chrome

**Comment by TheDeveloperD** [comment]
Ok then I will assign this task to you @apupneja

**Comment by apupneja** [comment]
Made a [PR](https://github.com/MSTC-DA-IICT/react-portfolio/pull/56) fixing the issue. Please take a look at it. Thanks.
