### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by kevinrawal** [MSTC-DA-IICT/react-portfolio#61]
Create avatar Logo For React Portfolio.

**Comment by kevinrawal** [comment]
i want to work on this

**Comment by TheDeveloperD** [comment]
Any updates @kevinrawal

**Comment by kevinrawal** [comment]
I am working on the logo I will complete it by tomorrow for sure.

**Comment by TheDeveloperD** [comment]
Yes @jyshdewangan . Assigning this task to you now.
