### ISSUE TITLE
Navbar issues in mobile view

### ISSUE THREAD

**Issue by ghost** [MSTC-DA-IICT/react-portfolio#64]
There are two different navbars i.e navbar large and navbar small. In the mobile view both of them appear and thus make it look messy. Look into the issue and try to solve it.

**Comment by TheDeveloperD** [comment]
> Hey I would like to work on this

Ok then assigning this task to you.

**Comment by TheDeveloperD** [comment]
Yes that would be appreciable.

**Comment by ayushgoswamiabr** [comment]
Ok
