### ISSUE TITLE
Design Projects Section

### ISSUE THREAD

**Issue by TheDeveloperD** [MSTC-DA-IICT/react-portfolio#7]
Design the projects section using css and js(if required). The css should be kept in a new file named Projects.css inside the css folder.

Create a gallery type view for showing the projects. 

Website color theme:
1. white
2. crimson

Both these colors are primary colors of the website. You may use any other colors for too but make sure that should not oppose the color theme.

Make sure you attach a snap of the changes made by you in your PR.

**Comment by khushali77** [comment]
Can I work on this issue?
If yes, then need to display Project name, tech stack used, github link, live link for each project, correct?

**Comment by TheDeveloperD** [comment]
OK Great. So I am assigning this task to you. 

Yes we can display project name, tech stack, github link, live link and **a snap** of each project's webpage.
That's what I mentioned in the issue, create something like image gallery and on hover we can display the above info.

**Comment by TheDeveloperD** [comment]
Thank you for your contribution. Closing this issue.
